name: Issue Template Automation

on:
  issues:
    types: [opened]

jobs:
  set-project-and-url:
    runs-on: ubuntu-latest

    steps:
      - name: Set project and URL
        uses: sahaspok/integration-testing-of-own@ref
        with:
          project: "integration test" # Replace with your project name
          column: "To do" # Replace with your project column name
          issue-number: ${{ github.event.issue.number }}
          custom-fields: |
            [
              {
                "name": "URL",
                "value": "test"
              }
            ]
          token: ${{ secrets.GITHUB_TOKEN }}
